### ISSUE TITLE
Not picking overriding parameter from repo secret

### ISSUE THREAD

**Issue by AlexNingfei** [whiteducksoftware/azure-arm-action#6] opened 2021-06-03 17:50 UTC
Hi there, 

I'm trying to override parameters which I coded in secrets. Doesn't look like it's picking up the value? 

      - uses: whiteducksoftware/azure-arm-action@v3.2
        id: deploy2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          templateLocation: ./adf-edw-sbx/ARMTemplateForFactory.json
          parameters: ./adf-edw-sbx/ARMTemplateParametersForFactory.json
          deploymentName: ADFUATRelease-whiteduck
          overrideParameters: factoryName=${{env.FACTORY_NAME}} SapHana_D1H_connectionString=${{secrets.SAPHANA_D1H_CONNECTIONSTRING}} SapHana_Q1H_connectionString=${{ secrets.SAPHANA_Q1H_CONNECTIONSTRING }} ls_bw4hanadb_d0b_connectionString=${{ secrets.SAPHANA_D0B_CONNECTIONSTRING }}

level=error msg="failed to load options: failed to parse inputs: Custom parser error: Found invalid pair, expected KEY=VALUE got SapHana_D1H_connectionString=***"

**Comment by mjisaak** [comment] 2021-06-03 18:27
I guess that the connection string contains characters like spaces that break the action. Can you try to surround the values with *quotes*?

**Comment by dalmasj** [comment] 2021-07-08 11:55
Hi there,
I have the same issue. My connection string contains spaces. 

level=error msg=failed to load options:"failed to parse inputs: Custom parser error: Found invalid pair, expected KEY=VALUE got LS_SQLDB_connectionString='***'"

I try to surround with single quote and double quotes too, still the same error

**Comment by nmeisenzahl** [comment] 2021-07-08 11:59
Hi @dalmasj. We're going to take a look at that. We will keep you posted.

**Comment by StiviiK** [comment] 2021-07-08 15:40
Hi @dalmasj and @AlexNingfei, I have an suspicion of what is going wrong in your case. But just to confirm, does your Connection String contain one or more `=` signs?

**Comment by dalmasj** [comment] 2021-07-08 15:51
Hi @StiviiK ,
Indeed the connection string contain multiple `=` signs

**Comment by StiviiK** [comment] 2021-07-08 16:26
@dalmasj could you please verify that the issue is now resolved with the latest `v3.2.1` version?

**Comment by dalmasj** [comment] 2021-07-09 12:01
![image](https://user-images.githubusercontent.com/83807850/125074494-a2d15280-e0bd-11eb-92d4-6fddbfa650e6.png)

I have the same issue

level=error msg="failed to load options: failed to parse inputs: Custom parser error: Found invalid pair, expected KEY=VALUE got LS_SQLDB_connectionString=Server=tcp:xxxx.database.windows.net,1433;Initial"

**Comment by StiviiK** [comment] 2021-07-09 12:40
Ah that's my mistake.. If you try the `v3.2.2` it should be working.

**Comment by dalmasj** [comment] 2021-07-09 13:02
![image](https://user-images.githubusercontent.com/83807850/125081444-4cb4dd00-e0c6-11eb-9de7-9ac3394ce3ff.png)

**Comment by StiviiK** [comment] 2021-07-09 13:23
Please try again now. 
The maintainer of the docker publish action did change the way on how tag are parsed.

**Comment by dalmasj** [comment] 2021-07-09 13:23
![image](https://user-images.githubusercontent.com/83807850/125084220-918e4300-e0c9-11eb-9f51-7a05058b3b25.png)
 I have a different error now

**Comment by StiviiK** [comment] 2021-07-09 13:24
How are you passing the connection string?
Does it look like this: https://github.com/whiteducksoftware/azure-arm-action/blob/master/.github/workflows/unit-tests.yaml#L39?

**Comment by dalmasj** [comment] 2021-07-09 13:31
Yes it's look like :

Server=tcp:xxx.database.windows.net,1433;Initial Catalog=xxx;Persist Security Info=False;User ID=xxx;Password=xxx

**Comment by StiviiK** [comment] 2021-07-09 13:33
Ah I think I see your problem, due to the spaces in the connection string you have to put it into quotes (`'`).
e.g.
```yaml
overrideParameters: |
   connectionString='Server=tcp:xxx.database.windows.net,1433;Initial Catalog=xxx;Persist Security Info=False;User ID=xxx;Password=xxx'
```

**Comment by dalmasj** [comment] 2021-07-09 13:46
Ok thanks @StiviiK  ! Inputs now working 👍 
Into (single) quotes it wont be a problem for SecureString ARM parameter  ?

I have now a totaly different issue : 
![image](https://user-images.githubusercontent.com/83807850/125086921-5b05f780-e0cc-11eb-8a2e-3c502562ac32.png)
Just before , Azure/login action with credential was ok
![image](https://user-images.githubusercontent.com/83807850/125087237-a0c2c000-e0cc-11eb-8fec-a5216c7202dd.png)

Do you have any idea about that ?

**Comment by StiviiK** [comment] 2021-07-09 13:51
Yes, currently the `azure/login` authentication is not supported for this action. You have to pass the Service Principal Credentials JSON to the `creds` input.
e.g. 
```yaml
with:
   creds: ${{ secrets.AZURE_CREDENTIALS }}
   [...]
```

**Comment by dalmasj** [comment] 2021-07-09 14:00
With `creds: ${{ secrets.AZURE_CREDENTIALS }}` still missing parameter "ressource "

**Comment by StiviiK** [comment] 2021-07-09 14:02
How does the SP JSON look like?
This one is working for me:
```
{
  "clientId": "***",
  "clientSecret": "***",
  "subscriptionId": "***",
  "tenantId": "***",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
  "resourceManagerEndpointUrl": "https://management.azure.com/",
  "activeDirectoryGraphResourceId": "https://graph.windows.net/",
  "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
  "galleryEndpointUrl": "https://gallery.azure.com/",
  "managementEndpointUrl": "https://management.core.windows.net/"
}
```

**Comment by dalmasj** [comment] 2021-07-09 14:07
I have just :  
`{
  "clientId": "***",
  "clientSecret": "***",
  "subscriptionId": "***",
  "tenantId": "***"}`

**Comment by StiviiK** [comment] 2021-07-09 14:09
Please add `"resourceManagerEndpointUrl": "https://management.azure.com/"` to the json.
Edit: I will improve that for the next version, and if you like I'll keep you updated.

**Comment by dalmasj** [comment] 2021-07-09 15:40
It's working thanks 👍 
Yes i'm interested

**Comment by StiviiK** [comment] 2021-07-09 16:59
Glad to hear that. 
I have fixed it (https://github.com/whiteducksoftware/azure-arm-action/commit/221096ebeb27b3422f1f966d69390c6c66c2bc03), will be releasing within the next days, then you can use the minimal JSON you've posted earlier.

**Closed as completed** 2021-07-09 16:59 UTC
Labels: bug

**Comment by StiviiK** [comment] 2021-07-13 16:21
@dalmasj I have great news for you, with the upcoming `v3.3` you can use the `Azure/login`for authentication and omit the `creds` parameter for our action entirely.
